### ISSUE TITLE
Permits muliple `,`

### ISSUE THREAD

**Issue by venkatarun95** [steadylearner/born#1]
Hello,

In [line 27 in `src/struct/public.rs`](https://github.com/steadylearner/born/blob/ce2cc62486b532f404210f71bb8ee8b927826ecc/src/struct/public.rs#L27), is there a reason you use `$(,)*` instead of `$(,)?`. As it is currently written, the macro allows the following:

```
public_struct!(
    pub struct Foo {
        x: u64,,,
    } 
);
```

which isn't part of the usual rust syntax. This problem doesn't affect any semantics and is a pretty minor issue

**Comment by steadylearner** [comment]
You are right. Thanks for the suggestion.

I tested both * and ? for the examples at this crate.

Rust compiler says there is unambiguous usage for ,, with * and it doesn't allow the macro compiled.

Then, with ?, macro rule itself doesn't allow the ,, to be used and error message is better.

I am not sure I will update this crate but I will update src/sturct/public.rs and src/struct/private.rs files with ?

Thanks
