### ISSUE TITLE
Cannot use macros inside the public_struct!

### ISSUE THREAD

**Issue by hatembentayeb** [steadylearner/born#2]

**Comment by steadylearner** [comment]
Can you share the code snippet you want to write with more description? Which macro you want to use?

Currently, its purpose is to reuse the same fields of a struct or enum only, but I can attempt to update if you help me to find what you want.

**Comment by steadylearner** [comment]
No responses from the user so I will close the issue.

**Comment by HonbraDev** [comment]
Sorry to necropost, but I think what they meant was that you can't use derive macros on the base. For example, you can't rename fields for use with Serde.

```rs
public_struct!(
    #[derive(Deserialize, Serialize)]
    pub struct MessageBase {
        #[serde(rename = "type")]
        pub kind: MessageType,
    }
);
```
